version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: library_postgres_db
    environment:
      POSTGRES_USER: lib_user
      POSTGRES_PASSWORD: lib_password
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
