package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"go-graphql-api/db"
	"go-graphql-api/graph/model"
	"strconv"
	"time"
)

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input model.CreateBookInput) (*model.Book, error) {
	dbBook := db.Book{
		Title:      input.Title,
		Author:     input.Author,
		ISBN:       input.Isbn,
		CategoryID: uint(input.CategoryID),
	}

	if err := r.DB.Create(&dbBook).Error; err != nil {
		return nil, err
	}

	// Preload Category information to return a complete structural model
	r.DB.Preload("Category").First(&dbBook, dbBook.ID)

	return &model.Book{
		ID:     strconv.Itoa(int(dbBook.ID)),
		Title:  dbBook.Title,
		Author: dbBook.Author,
		Isbn:   dbBook.ISBN,
		Category: &model.Category{
			ID:   strconv.Itoa(int(dbBook.Category.ID)),
			Name: dbBook.Category.Name,
		},
	}, nil
}

// CreateLoan is the resolver for the createLoan field.
func (r *mutationResolver) CreateLoan(ctx context.Context, input model.CreateLoanInput) (*model.Loan, error) {
	dbLoan := db.Loan{
		BookID:       uint(input.BookID),
		BorrowerName: input.BorrowerName,
		LoanDate:     time.Now(),
	}

	if err := r.DB.Create(&dbLoan).Error; err != nil {
		return nil, err
	}

	r.DB.Preload("Book.Category").First(&dbLoan, dbLoan.ID)

	return &model.Loan{
		ID:           strconv.Itoa(int(dbLoan.ID)),
		BorrowerName: dbLoan.BorrowerName,
		LoanDate:     dbLoan.LoanDate.Format("2006-01-02"),
		Book: &model.Book{
			ID:     strconv.Itoa(int(dbLoan.Book.ID)),
			Title:  dbLoan.Book.Title,
			Author: dbLoan.Book.Author,
			Isbn:   dbLoan.Book.ISBN,
			Category: &model.Category{
				ID:   strconv.Itoa(int(dbLoan.Book.Category.ID)),
				Name: dbLoan.Book.Category.Name,
			},
		},
	}, nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	var dbBooks []db.Book
	if err := r.DB.Preload("Category").Find(&dbBooks).Error; err != nil {
		return nil, err
	}

	var results []*model.Book
	for _, b := range dbBooks {
		results = append(results, &model.Book{
			ID:     strconv.Itoa(int(b.ID)),
			Title:  b.Title,
			Author: b.Author,
			Isbn:   b.ISBN,
			Category: &model.Category{
				ID:   strconv.Itoa(int(b.Category.ID)),
				Name: b.Category.Name,
			},
		})
	}
	return results, nil
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id string) (*model.Book, error) {
	var dbBook db.Book
	if err := r.DB.First(&dbBook, id).Error; err != nil {
		return nil, nil
	}

	return &model.Book{
		ID:     strconv.Itoa(int(dbBook.ID)),
		Title:  dbBook.Title,
		Author: dbBook.Author,
		Isbn:   dbBook.ISBN,
	}, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	var dbCategories []db.Category
	if err := r.DB.Find(&dbCategories).Error; err != nil {
		return nil, err
	}

	var results []*model.Category
	for _, c := range dbCategories {
		results = append(results, &model.Category{
			ID:   strconv.Itoa(int(c.ID)),
			Name: c.Name,
		})
	}
	return results, nil
}

// Loans is the resolver for the loans field.
func (r *queryResolver) Loans(ctx context.Context) ([]*model.Loan, error) {
	var dbLoans []db.Loan
	if err := r.DB.Preload("Book.Category").Find(&dbLoans).Error; err != nil {
		return nil, err
	}

	var results []*model.Loan
	for _, l := range dbLoans {
		var retDate *string
		if l.ReturnDate != nil {
			strDate := l.ReturnDate.Format("2006-01-02")
			retDate = &strDate
		}

		results = append(results, &model.Loan{
			ID:           strconv.Itoa(int(l.ID)),
			BorrowerName: l.BorrowerName,
			LoanDate:     l.LoanDate.Format("2006-01-02"),
			ReturnDate:   retDate,
			Book: &model.Book{
				ID:     strconv.Itoa(int(l.Book.ID)),
				Title:  l.Book.Title,
				Author: l.Book.Author,
				Isbn:   l.Book.ISBN,
				Category: &model.Category{
					ID:   strconv.Itoa(int(l.Book.Category.ID)),
					Name: l.Book.Category.Name,
				},
			},
		})
	}
	return results, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
