// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID       string    `json:"id"`
	Title    string    `json:"title"`
	Author   string    `json:"author"`
	Isbn     string    `json:"isbn"`
	Category *Category `json:"category,omitempty"`
}

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreateBookInput struct {
	Title      string `json:"title"`
	Author     string `json:"author"`
	Isbn       string `json:"isbn"`
	CategoryID int    `json:"categoryId"`
}

type CreateLoanInput struct {
	BookID       int    `json:"bookId"`
	BorrowerName string `json:"borrowerName"`
}

type Loan struct {
	ID           string  `json:"id"`
	Book         *Book   `json:"book"`
	BorrowerName string  `json:"borrowerName"`
	LoanDate     string  `json:"loanDate"`
	ReturnDate   *string `json:"returnDate,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
